#!/bin/bash

set -e
set -u

scripts_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
root_dir=$( dirname "$scripts_dir" )
site_dir="$root_dir/site"
ansible_dir="$root_dir/ansible"

echo "Building..."
pushd "$site_dir" > /dev/null
jekyll build
popd

echo "Deploying..."
pushd "$ansible_dir" > /dev/null
ansible-playbook pdavision.yml --ask-become-pass
popd
